#ifndef ARCHITECTURE_SEALBACKEND_SEAL_SEALCIPHERTEXT_H_
#define ARCHITECTURE_SEALBACKEND_SEAL_SEALCIPHERTEXT_H_

#include "../SealTensor.h"


#endif /* ARCHITECTURE_SEALBACKEND_SEAL_SEALCIPHERTEXT_H_ */
