PRINT_HEADERS=1
BATCH_SIZE=4096
HELIB_M=$(( BATCH_SIZE * 4 ))
SEAL_N=$(( BATCH_SIZE * 2 ))
HELIB_BITS=119
# HELIB_BITS=100 # Test to see if fewer bits affect accuracy at each scale
HELIB_C=2
SEAL_MAX_LOG_Q=202 # For 128-bit security
SEAL_BIG_PRIMES_BITS=60
# SEAL_BIG_PRIMES_BITS=50
for SCALE in 5 10 15 20 25 30 35 40:
do
    MAX_NR=1
    HELIB_SCALE=$SCALE
    SEAL_SCALE=$SCALE
    for TIMES_TO_SQUARE in {1..10}
    do
        ./1_power_raising $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR helib $HELIB_M $HELIB_BITS $HELIB_SCALE $HELIB_C
        # ./2_multiply_plain $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR helib $HELIB_M $HELIB_BITS $HELIB_SCALE $HELIB_C
        PRINT_HEADERS=0
    done
    for TIMES_TO_SQUARE in {1..10}
    do
        SEAL_NUM_SMALL_PRIMES=$(( ( $SEAL_MAX_LOG_Q-(2*$SEAL_BIG_PRIMES_BITS) ) / $SEAL_SCALE ))
        SEAL_NUM_SMALL_PRIMES=$(( $SEAL_NUM_SMALL_PRIMES < $TIMES_TO_SQUARE ? $SEAL_NUM_SMALL_PRIMES : $TIMES_TO_SQUARE ))
        ./1_power_raising $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR seal $SEAL_N $SEAL_BIG_PRIMES_BITS $SEAL_NUM_SMALL_PRIMES $SEAL_SCALE $SEAL_SCALE
        # ./2_multiply_plain $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR seal $SEAL_N $SEAL_BIG_PRIMES_BITS $SEAL_NUM_SMALL_PRIMES $SEAL_SCALE $SEAL_SCALE
    done
done

BATCH_SIZE=8192
HELIB_M=$(( BATCH_SIZE * 4 ))
SEAL_N=$(( BATCH_SIZE * 2 ))
SEAL_MAX_LOG_Q=411 # For 128-bit security
for SCALE in 5 10 15 20 25 30 35 40:
do
    MAX_NR=1
    HELIB_SCALE=$SCALE
    SEAL_SCALE=$SCALE
    for HELIB_C in 6 3 2
    do
        if [[ "$HELIB_C" -eq 6 ]]; then HELIB_BITS=358; fi
        if [[ "$HELIB_C" -eq 3 ]]; then HELIB_BITS=299; fi
        if [[ "$HELIB_C" -eq 2 ]]; then HELIB_BITS=239; fi
        for TIMES_TO_SQUARE in {1..10}
        do
            ./1_power_raising $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR helib $HELIB_M $HELIB_BITS $HELIB_SCALE $HELIB_C
            # ./2_multiply_plain $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR helib $HELIB_M $HELIB_BITS $HELIB_SCALE $HELIB_C
            PRINT_HEADERS=0
        done
    done
    for TIMES_TO_SQUARE in {1..10}
    do
        SEAL_NUM_SMALL_PRIMES=$(( ( $SEAL_MAX_LOG_Q-(2*$SEAL_BIG_PRIMES_BITS) ) / $SEAL_SCALE ))
        SEAL_NUM_SMALL_PRIMES=$(( $SEAL_NUM_SMALL_PRIMES < $TIMES_TO_SQUARE ? $SEAL_NUM_SMALL_PRIMES : $TIMES_TO_SQUARE ))
        ./1_power_raising $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR seal $SEAL_N $SEAL_BIG_PRIMES_BITS $SEAL_NUM_SMALL_PRIMES $SEAL_SCALE $SEAL_SCALE
        # ./2_multiply_plain $TIMES_TO_SQUARE $PRINT_HEADERS $MAX_NR seal $SEAL_N $SEAL_BIG_PRIMES_BITS $SEAL_NUM_SMALL_PRIMES $SEAL_SCALE $SEAL_SCALE
    done
done